"""Initial migration: create projects and issues tables

Revision ID: 224cd03114a0
Revises:
Create Date: 2026-05-28 12:30:17.415195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "224cd03114a0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("projectKey", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("chartEnabled", sa.Boolean(), nullable=True),
        sa.Column("useResolvedForChart", sa.Boolean(), nullable=True),
        sa.Column("subtaskingEnabled", sa.Boolean(), nullable=True),
        sa.Column("projectLeaderCanEditProjectLeader", sa.Boolean(), nullable=True),
        sa.Column("useWiki", sa.Boolean(), nullable=True),
        sa.Column("useFileSharing", sa.Boolean(), nullable=True),
        sa.Column("useWikiTreeView", sa.Boolean(), nullable=True),
        sa.Column("useOriginalImageSizeAtWiki", sa.Boolean(), nullable=True),
        sa.Column("useSubversion", sa.Boolean(), nullable=True),
        sa.Column("useGit", sa.Boolean(), nullable=True),
        sa.Column("textFormattingRule", sa.String(length=50), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("displayOrder", sa.Integer(), nullable=True),
        sa.Column("useDevAttributes", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(
        op.f("ix_projects_projectKey"), "projects", ["projectKey"], unique=True
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("projectId", sa.Integer(), nullable=False),
        sa.Column("issueKey", sa.String(length=255), nullable=False),
        sa.Column("keyId", sa.Integer(), nullable=False),
        sa.Column("issueTypeId", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("resolution", sa.String(length=255), nullable=True),
        sa.Column("priorityId", sa.Integer(), nullable=False),
        sa.Column("statusId", sa.Integer(), nullable=True),
        sa.Column("startDate", sa.String(length=10), nullable=True),
        sa.Column("dueDate", sa.String(length=10), nullable=True),
        sa.Column("assigneeId", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["projectId"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issues_id"), "issues", ["id"], unique=False)
    op.create_index(op.f("ix_issues_issueKey"), "issues", ["issueKey"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issues_issueKey"), table_name="issues")
    op.drop_index(op.f("ix_issues_id"), table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_projects_projectKey"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
